# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data
En este desafío, trabajaremos con los datos del cliente de una compañía de seguros, como lo hicimos en los dos laboratorios anteriores. Los datos se pueden encontrar aquí:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

Pero esta vez, obtuvimos datos nuevos, que se pueden encontrar en los siguientes 2 archivos CSV ubicados en los enlaces a continuación.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Tenga en cuenta que deberá limpiar y formatear los nuevos datos.

Observación:
- Una opción es combinar primero los tres conjuntos de datos y luego aplicar la función de limpieza al nuevo conjunto de datos combinado.
- Otra opción sería leer el archivo limpio que guardó en la práctica de laboratorio anterior, simplemente limpiar los dos archivos nuevos y concatenar los tres conjuntos de datos limpios.

In [1]:
import pandas as pd

In [2]:
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
url2 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url3 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"

In [3]:
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)
df3 = pd.read_csv(url3)
df1

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1.columns = df1.columns.str.lower().str.replace(' ', '_')
df2.columns = df2.columns.str.lower().str.replace(' ', '_')
df3.columns = df3.columns.str.lower().str.replace(' ', '_')
df1.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [5]:
df2.columns

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'total_claim_amount', 'policy_type', 'vehicle_class'],
      dtype='str')

In [6]:
df3.columns

Index(['customer', 'state', 'customer_lifetime_value', 'education', 'gender',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'total_claim_amount', 'vehicle_class'],
      dtype='str')

In [5]:
rename_dict = {'st': 'state'}
df1.rename(columns=rename_dict, inplace=True)
df2.rename(columns=rename_dict, inplace=True)
df3.rename(columns=rename_dict, inplace=True)

In [6]:
df_combinado = pd.concat([df1, df2, df3], ignore_index=True)
df_combinado

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [7]:
def clean_column_names(df):
    df = df.copy()

    df.drop_duplicates(inplace=True)
    df.dropna(how = 'all', inplace=True)

    if 'customer_lifetime_value' in df.columns:
        df['customer_lifetime_value'] = df['customer_lifetime_value'].astype(str).str.replace('%', '', regex=False)
        df['customer_lifetime_value'] = pd.to_numeric(df['customer_lifetime_value'], errors='coerce')
    
    if 'gender' in df.columns:
        df['gender'] = df['gender'].astype(str).str.lower().str.strip()
        gender_map = {'male': 'M', 'femal': 'F', 'female': 'F', 'f': 'F', 'm': 'M'}
        df['gender'] = df['gender'].replace(gender_map)
    
    if'state' in df.columns:
        df['state'] = df['state'].astype(str).str.lower().str.strip()
        state_map = {'ca': 'California', 'cali': 'California', 'AZ': 'Arizona', 'WA': 'Washington'}
        df['state'] = df['state'].replace(state_map)
    
    if 'number_of_open_complaints' in df.columns:
        df['number_of_open_complaints'] = df['number_of_open_complaints'].astype(str).apply(lambda x: x.split('/')[1] if '/' in x else x)
        df['number_of_open_complaints'] = pd.to_numeric(df['number_of_open_complaints'], errors='coerce')

    if 'income' in df.columns:
        df['income'] = df['income'].fillna(df['income'].median())

    return df

In [8]:
df_final = clean_column_names(df_combinado)
df_final.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,california,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323

# Challenge 2: Structuring Data

En este desafío, continuaremos trabajando con datos de clientes de una compañía de seguros, pero usaremos un conjunto de datos con más columnas, llamado marketing_customer_analysis.csv, que se puede encontrar en el siguiente enlace:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

Este conjunto de datos contiene información como datos demográficos del cliente, detalles de la política, información del vehículo y la respuesta del cliente a la última campaña de marketing. Nuestro objetivo es explorar y analizar estos datos realizando limpieza, formateo y estructuración de datos.

In [12]:
url4 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
df4 = pd.read_csv(url4)
df4.columns = df4.columns.str.lower().str.replace(' ', '_')

In [26]:
df4.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

In [ ]:
df4.head().T

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [27]:
df4['sales_channel'].unique()

<ArrowStringArray>
['Agent', 'Call Center', 'Branch', 'Web']
Length: 4, dtype: str

In [25]:
summary = df4.pivot_table(index='sales_channel', values='income', aggfunc='sum').reset_index()
summary['income'] = summary['income'].round(2)
summary = summary.sort_values(by='income', ascending=False)
summary

  sales_channel     income
0         Agent  152490152
1        Branch  113775608
2   Call Center   81055004
3           Web   62200103

2. Cree una tabla dinámica que muestre el valor promedio de vida del cliente por género y nivel educativo. Analice la tabla resultante para extraer ideas.

In [29]:
tabla_pivot = df4.pivot_table(index='education', columns='gender', values='customer_lifetime_value', aggfunc='mean')
tabla_pivot = tabla_pivot.round(2)
tabla_pivot

gender                      F        M
education
Bachelor              7874.27  7703.60
College               7748.82  8052.46
Doctor                7328.51  7415.33
High School or Below  8675.22  8149.69
Master                8157.05  8168.83

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here